### ISSUE TITLE
db2iseries connector

### ISSUE THREAD

**Issue by andrescolodrero** [strongloop/loopback-connector-db2iseries#2]
HI,
Is this connector to connect from a non IBMI source? 
I see you are using the ibmdb.. do you need a copy of DB2 running in the server?

Im creating a connector to use loopback in IBMi (for nodejs 4).
https://github.com/andrescolodrero/loopback-connector-ibmi

**Comment by qpresley** [comment]
This connector provides access from Linux/Unix/Windows/OSX to a DB2 iSeries database.  It requires only that the iSeries system is accessible through an ODBC connection.

**Comment by mxmrlt** [comment]
Hi @qpresley @andrescolodrero 

Are you sure it only requires an ODBC Connection? I mean unixODBC and IBM I Access for Linux for instance.
I'm pretty sure that it requires the IBM CLI Driver. Indeed I'm trying to make this connector work under OSX and Ubuntu and I get this error:

`[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968`

It seems that we need to also install DB2 Connect with a valid licence which obviously isn't free...

Unless I'm doing something wrong... Could you please help me?

Thank you.

**Comment by qpresley** [comment]
You do require a license to connect to DB2 iSeries or DB2z. The ibm_db module contains the IBM CLI Driver which is the official ODBC driver for all DB2 access from x86 platforms. It does not however get you out of License jail
